version: "3.8"

services:
  # first service only for the web-app
  node-app:
    build: .
    ports:
      - "3500:3500"
    environment:
      - PORT=3500
    env_file:
      - ./.env

#    confirm the service working sequence
    depends_on:
      - mongo
      - redis

  # second service for the mongoDB
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rickliyuehuang
      - MONGO_INITDB_ROOT_PASSWORD=passwordpassword

#    custom the volume to store the data for re-start the mongo container
    volumes:
      - mongo-db:/data/db

#  third service for redis
  redis:
    image: redis

volumes:
  mongo-db:
