version: "3.8"

services:
  #  fourth service for nginx
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3500:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro


  # first service only for the web-app
  node-app:
    build: .
#    remove ports because of nginx
#    ports:
#      - "3500:3500"
    environment:
      - PORT=3500
    env_file:
      - ./.env

#    confirm the service working sequence
    depends_on:
      - mongo
      - redis

  # second service for the mongoDB
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rickliyuehuang
      - MONGO_INITDB_ROOT_PASSWORD=passwordpassword

#    custom the volume to store the data for re-start the mongo container
    volumes:
      - mongo-db:/data/db

#  third service for redis
  redis:
    image: redis


volumes:
  mongo-db:
